name: Update Contribution

on:
  schedule:
    - cron: '0 9 * * *'  # Every day at 9 AM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Make a dummy commit
        run: |
          touch log.txt
          echo "Updated on $(date)" >> log.txt
          git config --local user.name "Awake-ctrl"
          git config --local user.email "kallepallysaikiran21@gmail.com"
          git add log.txt
          git commit -m "Auto-update contribution log" || echo "No changes to commit"
          git push origin HEAD
